/**
 * The PROJECTS flow's PID, end to end — what production does and a CLIENTS organisation does not.
 *
 *   BASE=http://127.0.0.1:<port> PASSCODE=<org passcode> node tools/projects-flow/pid-flow.e2e.mjs
 *
 * Run it against an organisation in the PROJECTS workspace flow, on a SCRATCH database (it creates,
 * restores and permanently deletes projects). docs/WORKSPACE_FLOWS.md: in PROJECTS a project's PID
 * is generated by an authority (a 5-minute hold, then attached) or requested from one; a returning
 * client adds a round under the same PID; the patent portal is on; the PID ledger is the registry.
 * None of the CLIENTS flow's routes exist here, and none of its fields are accepted.
 */
const BASE = process.env.BASE || 'http://127.0.0.1:4042';
const PASSCODE = process.env.PASSCODE || process.env.ORG_PASSCODE || 'cf-scratch-7713';
const PW = process.env.PW || 'sqip@1234';
const ADMIN = 'mohit@squarkip.com';        // Super Admin — a PID authority
const RUN = Date.now().toString(36).slice(-5);

let passed = 0; const fails = [];
const ok = (n, c, d = '') => {
  if (c) { passed++; console.log('  ok  ' + n); }
  else { fails.push(n + (d ? '\n      ' + d : '')); console.log('  FAIL ' + n + (d ? '\n      ' + d : '')); }
};
const step = s => console.log(`\n— ${s} —`);
const brief = r => `${r.status} ${JSON.stringify(r.data).slice(0, 200)}`;

function sess() {
  let cookie = '';
  return async (p, { method = 'GET', body, passcode } = {}) => {
    const headers = { 'content-type': 'application/json', ...(cookie ? { cookie } : {}), ...(passcode ? { 'x-org-passcode': passcode } : {}) };
    const r = await fetch(BASE + '/api/v1' + p, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
    const sc = r.headers.getSetCookie?.() ?? [];
    if (sc.length) cookie = sc.map(c => c.split(';')[0]).join('; ');
    const t = await r.text(); let d = null; try { d = t ? JSON.parse(t) : null; } catch { d = t; }
    return { status: r.status, data: d };
  };
}
const login = async (s, email) => (await s('/auth/login', { method: 'POST', body: { email, password: PW } })).status;
const idOf = async s => { const me = (await s('/auth/me')).data; return (me?.user ?? me)?.id; };

(async () => {
  const admin = sess();
  ok('the Super Admin signs in', [200, 201].includes(await login(admin, ADMIN)));
  const adminId = await idOf(admin);

  step('the organisation runs the PROJECTS flow');
  const orgs = (await admin('/organizations')).data ?? [];
  ok('its workspace flow is PROJECTS', orgs[0]?.workspaceFlow === 'PROJECTS', JSON.stringify(orgs[0]?.workspaceFlow));

  // An Employee: someone without project.generate_pid, who therefore REQUESTS a PID. Named rather
  // than searched for — logins are rate-limited, and the seeded Employees are known.
  let employee = null, employeeEmail = null;
  for (const email of [process.env.EMPLOYEE, 'ajay.sharma@squarkip.com', 'aman.sharma@squarkip.com', 'drishti.jain@squarkip.com', 'rajesh.joshi@squarkip.com'].filter(Boolean)) {
    const probe = sess();
    if (![200, 201].includes(await login(probe, email))) continue;
    const eff = (await probe('/me/effective-permissions')).data;
    const codes = eff?.codes ?? [];
    if (!eff?.isSuperAdmin && codes.includes('project.create') && !codes.includes('project.generate_pid')) {
      employee = probe; employeeEmail = email; break;
    }
  }
  ok('setup: a member who may create a project but not issue a PID', !!employee, 'none found');
  if (!employee) return report();
  console.log(`      (${employeeEmail})`);

  step('Generate PID: a five-minute hold, then attached to a new project');
  // A hold left over from an earlier run would refuse the generate below; it expires on its own.
  const held = (await admin('/projects/pid-reservation')).data?.reservation;
  if (held) console.log(`      (an earlier hold ${held.pid} is still live — attaching it)`);
  const gen = held ? { status: 201, data: { pid: held.pid, createdAt: held.createdAt, expiresAt: held.expiresAt } }
    : await admin('/projects/generate-pid', { method: 'POST' });
  const pid1 = gen.data?.pid;
  ok('Generate PID answers a PID in the organisation\'s series', gen.status === 201 && /^SQ_\d{2}_\d{2}_\d{3,}$/.test(pid1 ?? ''), brief(gen));
  const holdMin = (new Date(gen.data?.expiresAt) - new Date(gen.data?.createdAt)) / 60000;
  ok('…held for five minutes', holdMin > 4.9 && holdMin <= 5.05, `${holdMin} min`);
  const again = await admin('/projects/generate-pid', { method: 'POST' });
  ok('a second Generate while one is held is refused, in words',
    again.status === 400 && /already hold an un-attached Project ID/.test(again.data?.message ?? ''), brief(again));
  const mine = (await admin('/projects/pid-reservation')).data;
  ok('the hold is the caller\'s current reservation', mine?.reservation?.pid === pid1, JSON.stringify(mine));
  ok('next-pid previews a number', (await admin('/projects/next-pid')).status === 200);

  const p1 = await admin('/projects', { method: 'POST', body: { title: `PID flow ${RUN}`, pid: pid1 } });
  ok('the authority creates a project with the PID it generated', p1.status === 201 && p1.data?.code === pid1, brief(p1));
  ok('…and the hold is spent', (await admin('/projects/pid-reservation')).data?.reservation == null);
  let ledger = (await admin('/projects/pid-ledger')).data ?? [];
  const row1 = ledger.find(r => r.pid === pid1);
  ok('the PID ledger lists it as attached to the project', row1?.status === 'ATTACHED' && row1?.project?.title === `PID flow ${RUN}`,
    JSON.stringify(row1)?.slice(0, 200));

  step('Request a PID: an Employee asks an authority, who fulfils it');
  const auth = (await employee('/projects/pid-authorities')).data ?? [];
  ok('the Employee is offered the PID authorities', auth.some(a => a.id === adminId), `${auth.length} authorities`);
  const elig = (await employee('/projects/eligible-managers')).data;
  ok('…and told it does not issue PIDs itself', elig?.canIssuePid === false, JSON.stringify(elig)?.slice(0, 120));
  const noAuth = await employee('/projects', { method: 'POST', body: { title: `No authority ${RUN}` } });
  ok('creating without naming an authority is refused, in words',
    noAuth.status === 400 && /Select who should assign the Project ID/.test(noAuth.data?.message ?? ''), brief(noAuth));
  const selfId = await idOf(employee);
  const p2 = await employee('/projects', {
    method: 'POST', body: { title: `PID requested ${RUN}`, pidAssigneeId: adminId, managerId: selfId },
  });
  ok('the Employee creates a project with its PID pending', p2.status === 201 && p2.data?.code == null, brief(p2));
  const queue = (await admin('/projects/pid-requests')).data ?? [];
  const request = queue.find(q => q.projectId === p2.data?.id);
  ok('the request reaches the authority\'s queue', !!request, `${queue.length} in the queue`);
  const gen2 = await admin('/projects/generate-pid', { method: 'POST' });
  const pid2 = gen2.data?.pid;
  const ful = await admin(`/projects/pid-requests/${request?.id}/fulfill`, { method: 'POST', body: { pid: pid2 } });
  ok('the authority fulfils it with a generated PID', ful.status === 201 && ful.data?.pid === pid2, brief(ful));
  ok('the project now carries that PID', (await employee(`/projects/${p2.data?.id}`)).data?.code === pid2);
  ok('…and the request has left the queue', !((await admin('/projects/pid-requests')).data ?? []).some(q => q.id === request?.id));
  const twice = await admin(`/projects/pid-requests/${request?.id}/fulfill`, { method: 'POST', body: { pid: pid2 } });
  ok('fulfilling it twice is refused', twice.status === 400 && /already been resolved/.test(twice.data?.message ?? ''), brief(twice));

  step('A returning client: another project under the same PID');
  const round = await admin(`/projects/${p1.data?.id}/rounds`, { method: 'POST', body: { title: `PID flow ${RUN} — round 2` } });
  ok('a round is added under the PID', round.status === 201 && round.data?.code === pid1 && round.data?.roundSeq === 2, brief(round));
  const rounds = (await admin(`/projects/${p1.data?.id}/rounds`)).data;
  ok('the rounds read under their PID', rounds?.pid === pid1 && rounds?.multiRound === true && rounds?.rounds?.length === 2,
    JSON.stringify(rounds)?.slice(0, 160));

  step('The patent portal and client codes are on');
  for (const path of ['/patents', '/patents/options', '/clients', '/client-ledger', `/projects/${p1.data?.id}/patent-numbers`]) {
    const r = await admin(path);
    ok(`${path} answers`, r.status === 200, brief(r));
  }
  const tag = await admin(`/projects/${p1.data?.id}/patents`, { method: 'PUT', body: { patentIds: [] } });
  ok('tagging patents on a project works', tag.status === 200, brief(tag));

  step('Task lists are production\'s: a name and an order');
  const lists = (await admin(`/projects/${p1.data?.id}/tasklists`)).data ?? [];
  const def = lists.find(l => l.isDefault);
  ok('a new project has its default "General" list', def?.name === 'General', JSON.stringify(lists.map(l => l.name)));
  const tl = await admin(`/projects/${p1.data?.id}/tasklists`, { method: 'POST', body: { name: 'Second pass' } });
  ok('a task list is created from a name', tl.status === 201 && tl.data?.name === 'Second pass', brief(tl));
  const dated = await admin(`/projects/${p1.data?.id}/tasklists`, { method: 'POST', body: { name: 'Dated', dueDate: '2026-12-01' } });
  ok('…and nothing else — a task group\'s fields are refused', dated.status === 400, brief(dated));
  const delDef = await admin(`/projects/${p1.data?.id}/tasklists/${def?.id}`, { method: 'DELETE' });
  ok('the default list cannot be deleted, in production\'s words',
    delDef.status === 400 && delDef.data?.message === 'The default "General" task list cannot be deleted.', brief(delDef));

  step('The CLIENTS flow\'s routes and fields do not exist here');
  for (const [method, path] of [
    ['GET', '/projects/cid-ledger'], ['GET', '/client-groups'],
    // The cross-client task-group browser. Task groups are a CLIENTS idea — the PROJECTS flow has
    // task lists, inside one matter — so the whole controller is absent here rather than answering
    // with an empty list, which would read as "no work found" (docs/WORKSPACE_FLOWS.md).
    ['GET', '/task-groups'], ['GET', '/task-groups?search=claim'],
    // "Start a whole piece of client work from the board" — a client, its client group, its task
    // groups and its CID in one call. Every noun in that sentence is a CLIENTS one, and the
    // PROJECTS board has no task CRUD to hang it off.
    ['POST', '/capacity/clients'], ['POST', '/capacity/tasks'],
    ['GET', `/projects/${p1.data?.id}/cid-move?mode=REASSIGN`], ['GET', `/projects/${p1.data?.id}/cid-move/targets`],
    ['POST', `/projects/${p1.data?.id}/cid/reassign`], ['POST', `/projects/${p1.data?.id}/tasklists/${tl.data?.id}/complete`],
  ]) {
    const r = await admin(path, { method, ...(method === 'POST' ? { body: {}, passcode: PASSCODE } : {}) });
    ok(`${method} ${path.replace(p1.data?.id ?? '§', ':id').replace(tl.data?.id ?? '§', ':tl')} → 404`, r.status === 404, brief(r));
  }
  const grouped = await admin('/projects', { method: 'POST', body: { title: `Grouped ${RUN}`, clientGroupId: 'x' } });
  ok('a client group on create is refused as an unknown field', grouped.status === 400 &&
    JSON.stringify(grouped.data?.message).includes('clientGroupId should not exist'), brief(grouped));
  const withGroup = await admin('/projects', { method: 'POST', body: { title: `First group ${RUN}`, taskGroup: { name: 'x' } } });
  ok('…and so is a first task group', withGroup.status === 400, brief(withGroup));
  const patch = await admin(`/projects/${p1.data?.id}`, { method: 'PATCH', body: { clientGroupId: null } });
  ok('an edit naming a client group is refused as an unknown field', patch.status === 400, brief(patch));

  step('Admin → Data: production\'s restore and permanent delete');
  const del = await admin(`/projects/${p2.data?.id}`, { method: 'DELETE' });
  ok('the requested project is deleted', [200, 204].includes(del.status), brief(del));
  const res = await admin(`/admin/data/projects/${p2.data?.id}/restore`, { method: 'POST' });
  ok('restore brings it back', res.status === 201 && res.data?.id === p2.data?.id, brief(res));
  ok('…as production answers it (no CID in the reply)', res.data && !('cid' in res.data) && !('phase' in res.data), brief(res));
  ok('…ACTIVE, with its PID', (await admin(`/projects/${p2.data?.id}`)).data?.projectPhase === 'ACTIVE');
  await admin(`/projects/${p2.data?.id}`, { method: 'DELETE' });
  const purge = await admin(`/projects/${p2.data?.id}/permanent?confirm=${encodeURIComponent(`PID requested ${RUN}`)}`,
    { method: 'DELETE', passcode: PASSCODE });
  ok('a Super Admin destroys it for good', purge.status === 200, brief(purge));
  ok('…its PID reservation is discontinued, as production did', purge.data?.deleted?.pidReservationsDiscontinued === 1, brief(purge));
  ledger = (await admin('/projects/pid-ledger')).data ?? [];
  ok('the PID ledger keeps the number, discontinued', ledger.find(r => r.pid === pid2)?.status === 'DISCONTINUED',
    JSON.stringify(ledger.find(r => r.pid === pid2))?.slice(0, 160));

  report();
})().catch(e => { console.error(e); process.exit(1); });

function report() {
  console.log(`\n${passed} passed, ${fails.length} failed`);
  if (fails.length) { console.log('\nFailures:\n  ' + fails.join('\n  ')); process.exit(1); }
}
