'use client';

import { Fragment, useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import clsx from 'clsx';
import { X, Loader, KeyRound, Download, ChevronRight, ChevronDown } from 'lucide-react';
import { api, type PidLedgerEntry } from '@/lib/api';
import { formatDate, formatDateTimeIST } from '@/lib/date';

const STATUS_META: Record<PidLedgerEntry['status'], { label: string; cls: string }> = {
  ATTACHED:     { label: 'Working',      cls: 'bg-green-100 text-green-700' },
  RESERVED:     { label: 'Reserved',     cls: 'bg-amber-100 text-amber-700' },
  DISCONTINUED: { label: 'Discontinued', cls: 'bg-red-100 text-red-700' },
};

type FilterKey = 'All' | 'Working' | 'Discontinued' | 'Reserved';
const FILTERS: FilterKey[] = ['All', 'Working', 'Discontinued', 'Reserved'];

const statusLabel = (s: string) => STATUS_META[s as PidLedgerEntry['status']]?.label ?? s;

/** Quote a CSV cell (wrap in quotes, escape embedded quotes) so commas/newlines are safe. */
function csvCell(v: unknown): string {
  const s = v == null ? '' : String(v);
  return `"${s.replace(/"/g, '""')}"`;
}

/** Build + download a CSV of the (filtered) ledger rows — every project detail. Opens in Excel. */
function exportCsv(rows: PidLedgerEntry[]) {
  const header = [
    'PID', 'Status', 'Project', 'Description', 'Type', 'Priority', 'Client', 'Progress %',
    'Start', 'Deadline', 'Client Deadline', 'Patents', 'Members', 'Created by', 'Project created',
    'Generated by', 'PID created', 'PID resolved',
  ];
  const p = (r: PidLedgerEntry) => r.project;
  const body = rows.map(r => [
    r.pid, statusLabel(r.status), p(r)?.title ?? '', p(r)?.description ?? '', p(r)?.type ?? '',
    p(r)?.priority ?? '', p(r)?.client ?? '', p(r)?.progress != null ? `${p(r)!.progress}` : '',
    p(r)?.startDate ? formatDate(p(r)!.startDate!) : '',
    p(r)?.dueDate ? formatDate(p(r)!.dueDate!) : '',
    p(r)?.clientDueDate ? formatDate(p(r)!.clientDueDate!) : '',
    (p(r)?.patents ?? []).join('; '),
    (p(r)?.members ?? []).map(m => `${m.name} (${m.role})`).join('; '),
    p(r)?.createdBy ?? '', p(r)?.createdAt ? formatDate(p(r)!.createdAt!) : '',
    r.generatedBy, formatDateTimeIST(r.createdAt), r.resolvedAt ? formatDateTimeIST(r.resolvedAt) : '',
  ]);
  const csv = [header, ...body].map(row => row.map(csvCell).join(',')).join('\r\n');
  const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' }); // BOM → Excel opens UTF-8 cleanly
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `pid-ledger-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/** Admin/Super-Admin ledger of every Project ID — working, discontinued, and full history. */
export function PidLedgerModal({ onClose }: { onClose: () => void }) {
  const [filter, setFilter] = useState<FilterKey>('All');
  const [openId, setOpenId] = useState<string | null>(null); // expanded detail row
  const { data: rows = [], isLoading, isError, refetch } = useQuery({
    queryKey: ['pid-ledger'],
    queryFn: () => api.projects.pidLedger(),
    staleTime: 15_000,
  });

  const filtered = useMemo(() => rows.filter(r => {
    if (filter === 'Working') return r.status === 'ATTACHED';
    if (filter === 'Discontinued') return r.status === 'DISCONTINUED';
    if (filter === 'Reserved') return r.status === 'RESERVED';
    return true;
  }), [rows, filter]);

  const counts = useMemo(() => ({
    working: rows.filter(r => r.status === 'ATTACHED').length,
    discontinued: rows.filter(r => r.status === 'DISCONTINUED').length,
    total: rows.length,
  }), [rows]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-3xl mx-4 max-h-[calc(100dvh-2rem)] flex flex-col">
        <div className="flex items-center justify-between px-6 py-5 border-b border-gray-100 shrink-0">
          <div>
            <h2 className="text-lg font-semibold text-gray-900 flex items-center gap-2"><KeyRound size={18} className="text-brand-600" /> Project ID Ledger</h2>
            <p className="text-sm text-gray-500 mt-0.5">
              {counts.working} working · {counts.discontinued} discontinued · {counts.total} total
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => exportCsv(filtered)}
              disabled={filtered.length === 0}
              title="Export the current view to CSV (opens in Excel)"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50"
            >
              <Download size={14} /> Export CSV
            </button>
            <button onClick={onClose} className="p-2 rounded-lg text-gray-400 hover:bg-gray-100"><X size={18} /></button>
          </div>
        </div>

        <div className="px-6 pt-4 shrink-0 flex items-center gap-1.5">
          {FILTERS.map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={clsx('px-3 py-1 text-xs font-medium rounded-full transition-colors',
                filter === f ? 'bg-brand-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200')}>
              {f}
            </button>
          ))}
          <span className="ml-auto text-[11px] text-gray-400">Click a row for full details</span>
        </div>

        <div className="px-6 py-4 overflow-auto">
          {isLoading && <p className="text-sm text-gray-400 flex items-center gap-2 py-8 justify-center"><Loader size={14} className="animate-spin" /> Loading…</p>}
          {!isLoading && isError && (
            <div className="text-sm text-gray-500 text-center py-8">
              <p className="text-red-500">Couldn’t load the PID ledger.</p>
              <button onClick={() => refetch()} className="mt-2 text-brand-600 hover:underline">Retry</button>
            </div>
          )}
          {!isLoading && !isError && (
            <div className="overflow-x-auto">
              <table className="w-full text-left min-w-[640px]">
                <thead>
                  <tr className="border-b border-gray-200 bg-gray-50">
                    {['', 'PID', 'Status', 'Project', 'Generated by', 'Created', 'Resolved'].map((h, i) => (
                      <th key={i} className="px-3 py-2 text-[11px] font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {filtered.length === 0 && (
                    <tr><td colSpan={7} className="px-3 py-10 text-center text-sm text-gray-400">No Project IDs in this view yet.</td></tr>
                  )}
                  {filtered.map(r => {
                    const meta = STATUS_META[r.status]
                      ?? { label: r.status ? r.status.charAt(0) + r.status.slice(1).toLowerCase() : 'Unknown', cls: 'bg-gray-100 text-gray-500' };
                    const open = openId === r.id;
                    return (
                      <Fragment key={r.id}>
                        <tr className="hover:bg-gray-50 cursor-pointer" onClick={() => setOpenId(open ? null : r.id)}>
                          <td className="px-3 py-2.5 text-gray-400">{open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</td>
                          <td className="px-3 py-2.5 text-xs font-mono font-medium text-gray-800 whitespace-nowrap">{r.pid}</td>
                          <td className="px-3 py-2.5">
                            <span className={clsx('inline-flex px-2 py-0.5 rounded-full text-[11px] font-medium', meta.cls)}>{meta.label}</span>
                          </td>
                          <td className="px-3 py-2.5 text-sm text-gray-700 max-w-[200px] truncate" title={r.project?.title ?? ''}>
                            {r.project ? r.project.title : <span className="text-gray-400">—</span>}
                          </td>
                          <td className="px-3 py-2.5 text-xs text-gray-600 whitespace-nowrap">{r.generatedBy}</td>
                          <td className="px-3 py-2.5 text-xs text-gray-500 whitespace-nowrap">{formatDateTimeIST(r.createdAt)}</td>
                          <td className="px-3 py-2.5 text-xs text-gray-500 whitespace-nowrap">{r.resolvedAt ? formatDateTimeIST(r.resolvedAt) : '—'}</td>
                        </tr>
                        {open && (
                          <tr className="bg-gray-50/60">
                            <td />
                            <td colSpan={6} className="px-3 py-3">
                              {r.project ? (
                                <div className="grid grid-cols-1 sm:grid-cols-3 gap-x-8 gap-y-2 text-xs">
                                  <div><span className="text-gray-400">Project</span><p className="text-gray-800 font-medium">{r.project.title}</p></div>
                                  <div><span className="text-gray-400">Type</span><p className="text-gray-800">{r.project.type ?? '—'}</p></div>
                                  <div><span className="text-gray-400">Phase</span><p className="text-gray-800">{r.project.phase ?? '—'}</p></div>
                                  <div><span className="text-gray-400">Priority</span><p className="text-gray-800">{r.project.priority ?? '—'}</p></div>
                                  <div><span className="text-gray-400">Progress</span><p className="text-gray-800">{r.project.progress != null ? `${r.project.progress}%` : '—'}</p></div>
                                  <div><span className="text-gray-400">Client</span><p className="text-gray-800">{r.project.client ?? '—'}</p></div>
                                  <div><span className="text-gray-400">Start</span><p className="text-gray-800">{r.project.startDate ? formatDate(r.project.startDate) : '—'}</p></div>
                                  <div><span className="text-gray-400">Deadline</span><p className="text-gray-800">{r.project.dueDate ? formatDate(r.project.dueDate) : '—'}</p></div>
                                  <div><span className="text-gray-400">Client Deadline</span><p className="text-gray-800">{r.project.clientDueDate ? formatDate(r.project.clientDueDate) : '—'}</p></div>
                                  <div><span className="text-gray-400">Created by</span><p className="text-gray-800">{r.project.createdBy ?? '—'}</p></div>
                                  <div><span className="text-gray-400">Project created</span><p className="text-gray-800">{r.project.createdAt ? formatDate(r.project.createdAt) : '—'}</p></div>
                                  {r.project.description && (
                                    <div className="sm:col-span-3"><span className="text-gray-400">Description</span><p className="text-gray-800 whitespace-pre-wrap">{r.project.description}</p></div>
                                  )}
                                  {r.project.patents && r.project.patents.length > 0 && (
                                    <div className="sm:col-span-3"><span className="text-gray-400">Patents</span>
                                      <div className="flex flex-wrap gap-1.5 mt-1">
                                        {r.project.patents.map((h, i) => <span key={i} className="px-2 py-0.5 rounded-md bg-amber-50 text-amber-700 font-mono ring-1 ring-amber-100">{h}</span>)}
                                      </div>
                                    </div>
                                  )}
                                  <div className="sm:col-span-3">
                                    <span className="text-gray-400">Members</span>
                                    {r.project.members && r.project.members.length > 0 ? (
                                      <div className="flex flex-wrap gap-1.5 mt-1">
                                        {r.project.members.map((m, i) => (
                                          <span key={i} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-white border border-gray-200 text-gray-700">
                                            {m.name}<span className="text-gray-400">· {m.role}</span>
                                          </span>
                                        ))}
                                      </div>
                                    ) : <p className="text-gray-400">No active members.</p>}
                                  </div>
                                </div>
                              ) : (
                                <p className="text-xs text-gray-400">This PID isn’t attached to a project (reserved or discontinued-before-use).</p>
                              )}
                            </td>
                          </tr>
                        )}
                      </Fragment>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
