'use client';

import { Fragment, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import clsx from 'clsx';
import { Loader, Download, ChevronRight, ChevronDown, Search, RotateCcw, ExternalLink } from 'lucide-react';
import { api, type PidLedgerEntry, type PidLedgerState } from '@/lib/api';
import { formatDate, formatDateTimeIST } from '@/lib/date';
import { usePermissions } from '@/lib/permissions-context';
import { useToast } from '@/components/ui/Toast';
import { projectTypeLabel } from '@/lib/mock-data';

// The badge reflects the PID's REAL lifecycle (derived server-side from the project's phase).
// Aligned with the project-phase palette: Active/Working = brand blue, Completed = green,
// Closed = slate, Cancelled/Discontinued = red (Reserved = amber for "pending").
export const STATE_META: Record<PidLedgerState, { label: string; cls: string }> = {
  WORKING:      { label: 'Working',      cls: 'bg-brand-100 text-brand-700' },
  COMPLETED:    { label: 'Completed',    cls: 'bg-green-100 text-green-700' },
  CLOSED:       { label: 'Closed',       cls: 'bg-slate-200 text-slate-600' },
  RESERVED:     { label: 'Reserved',     cls: 'bg-amber-100 text-amber-700' },
  DISCONTINUED: { label: 'Discontinued', cls: 'bg-red-100 text-red-700' },
};

type FilterKey = 'All' | 'Working' | 'Completed' | 'Closed' | 'Reserved' | 'Discontinued';
const FILTERS: FilterKey[] = ['All', 'Working', 'Completed', 'Closed', 'Reserved', 'Discontinued'];
// Which derived state each non-"All" filter keeps.
const FILTER_STATE: Record<Exclude<FilterKey, 'All'>, PidLedgerState> = {
  Working: 'WORKING', Completed: 'COMPLETED', Closed: 'CLOSED', Reserved: 'RESERVED', Discontinued: 'DISCONTINUED',
};

const stateLabel = (s: PidLedgerState) => STATE_META[s]?.label ?? s;

/** Quote a CSV cell (wrap in quotes, escape embedded quotes) so commas/newlines are safe. */
function csvCell(v: unknown): string {
  const s = v == null ? '' : String(v);
  return `"${s.replace(/"/g, '""')}"`;
}

/**
 * CSV of the (filtered) ledger — ONE ROW PER PROJECT, not per PID.
 *
 * A PID can hold several projects for a returning client, so a row-per-PID would silently drop
 * every earlier piece of work. The PID and a Project # column tie the rows back together.
 */
function exportCsv(rows: PidLedgerEntry[]) {
  const header = [
    'PID', 'PID Status', 'Projects under PID', 'Project #',
    'Project', 'Description', 'Type', 'Phase', 'Priority', 'Client', 'Progress %',
    'Start', 'End / Deadline', 'Client Deadline',
    'Client Delivered', 'Working Hours', 'Actual Hours', 'Hours Variance', 'Completed On', 'Closed On',
    'Patents', 'Members', 'Created by', 'Project created',
    'Generated by', 'PID created', 'PID resolved',
  ];
  const body = rows.flatMap(r => {
    const rounds = r.rounds ?? [];
    // A PID with no project yet (reserved / discontinued-before-use) still gets its own row.
    if (!rounds.length) {
      return [[r.pid, stateLabel(r.state), 0, '', ...Array(20).fill(''), r.generatedBy,
               formatDateTimeIST(r.createdAt), r.resolvedAt ? formatDateTimeIST(r.resolvedAt) : '']];
    }
    return rounds.map(rd => [
      r.pid, stateLabel(r.state), rounds.length, rd.round,
      rd.title, rd.description ?? '', rd.type ?? '', rd.phase ?? '', rd.priority ?? '', rd.client ?? '',
      rd.progress != null ? `${rd.progress}` : '',
      rd.startDate ? formatDate(rd.startDate) : '',
      rd.dueDate ? formatDate(rd.dueDate) : '',
      rd.clientDueDate ? formatDate(rd.clientDueDate) : '',
      rd.clientDeliveryDate ? formatDateTimeIST(rd.clientDeliveryDate) : '',
      rd.workingHours ?? '', rd.actualHours ?? '',
      rd.actualHours != null && rd.workingHours != null
        ? Math.round((rd.actualHours - rd.workingHours) * 10) / 10 : '',
      rd.completedAt ? formatDateTimeIST(rd.completedAt) : '',
      rd.closedAt ? formatDateTimeIST(rd.closedAt) : '',
      (rd.patents ?? []).join('; '),
      (rd.members ?? []).map(m => `${m.name} (${m.role})`).join('; '),
      rd.createdBy ?? '', rd.createdAt ? formatDate(rd.createdAt) : '',
      r.generatedBy, formatDateTimeIST(r.createdAt), r.resolvedAt ? formatDateTimeIST(r.resolvedAt) : '',
    ]);
  });
  const csv = [header, ...body].map(row => row.map(csvCell).join(',')).join('\r\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' }); // BOM → Excel opens UTF-8 cleanly
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `pid-ledger-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * The Project ID ledger body — counts, filters, CSV export, and an expandable detail table of
 * every PID with the full project context. Chrome-free so it renders both as a full page (the
 * admin-only /pid-ledger module) and inside the modal wrapper. Data is admin-gated server-side.
 */
export function PidLedgerView({ toolbarExtra }: { toolbarExtra?: React.ReactNode }) {
  const [filter, setFilter] = useState<FilterKey>('All');
  const [search, setSearch] = useState('');
  const [openId, setOpenId] = useState<string | null>(null); // expanded detail row
  const [reinitId, setReinitId] = useState('');              // project currently being revived
  const qc = useQueryClient();
  const { can } = usePermissions();
  const { toast } = useToast();
  const canReinit = can('project.update');

  /**
   * Bring a finished matter back to work UNDER THE SAME PID. This is the ledger's whole reason for
   * offering it: a returning client quotes the number they already have, and the admin finds it
   * here rather than hunting the project down and recreating it.
   */
  async function reinitialize(projectId: string, title: string) {
    if (!confirm(`Re-initialize "${title}"?\n\nIt goes back to Active with the SAME Project ID and all its existing data.`)) return;
    setReinitId(projectId);
    try {
      await api.projects.reinitialize(projectId);
      qc.invalidateQueries({ queryKey: ['pid-ledger'] });
      qc.invalidateQueries({ queryKey: ['projects'] });
      toast(`"${title}" is active again — same Project ID.`, 'success');
    } catch (e) {
      toast(e instanceof Error ? e.message : 'Could not re-initialize the project.', 'error');
    } finally { setReinitId(''); }
  }
  const { data: rows = [], isLoading, isError, refetch } = useQuery({
    queryKey: ['pid-ledger'],
    queryFn: () => api.projects.pidLedger(),
    staleTime: 15_000,
  });

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    return rows.filter(r => {
      // State filter (derived lifecycle, not the raw reservation).
      if (filter !== 'All' && r.state !== FILTER_STATE[filter]) return false;
      // Free-text search: PID, project title, or client name.
      if (q) {
        const hay = `${r.pid} ${r.project?.title ?? ''} ${r.project?.client ?? ''}`.toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    });
  }, [rows, filter, search]);

  const counts = useMemo(() => {
    const c: Record<PidLedgerState, number> = { WORKING: 0, COMPLETED: 0, CLOSED: 0, RESERVED: 0, DISCONTINUED: 0 };
    for (const r of rows) c[r.state] = (c[r.state] ?? 0) + 1;
    return { ...c, total: rows.length };
  }, [rows]);

  return (
    <div className="flex flex-col min-h-0">
      <div className="flex items-center justify-between gap-3 flex-wrap shrink-0">
        <p className="text-sm text-gray-500">
          {counts.WORKING} working · {counts.COMPLETED} completed · {counts.CLOSED} closed · {counts.DISCONTINUED} discontinued · {counts.total} total
        </p>
        <div className="flex items-center gap-2">
          <div className="relative">
            <Search size={13} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400" />
            <input
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search PID or client…"
              className="w-52 pl-7 pr-2 py-1.5 text-xs border border-gray-200 rounded-lg focus:outline-none focus:border-brand-400"
            />
          </div>
          <button
            onClick={() => exportCsv(filtered)}
            disabled={filtered.length === 0}
            title="Export the current view to CSV (opens in Excel)"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50"
          >
            <Download size={14} /> Export CSV
          </button>
          {toolbarExtra}
        </div>
      </div>

      <div className="pt-4 shrink-0 flex items-center gap-1.5 flex-wrap">
        {FILTERS.map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={clsx('px-3 py-1 text-xs font-medium rounded-full transition-colors',
              filter === f ? 'bg-brand-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200')}>
            {f}{f !== 'All' && counts[FILTER_STATE[f]] > 0 ? ` (${counts[FILTER_STATE[f]]})` : ''}
          </button>
        ))}
        <span className="ml-auto text-[11px] text-gray-400">Click a row for full details</span>
      </div>

      <div className="py-4 overflow-auto">
        {isLoading && <p className="text-sm text-gray-400 flex items-center gap-2 py-8 justify-center"><Loader size={14} className="animate-spin" /> Loading…</p>}
        {!isLoading && isError && (
          <div className="text-sm text-gray-500 text-center py-8">
            <p className="text-red-500">Couldn’t load the PID ledger.</p>
            <button onClick={() => refetch()} className="mt-2 text-brand-600 hover:underline">Retry</button>
          </div>
        )}
        {!isLoading && !isError && (
          <div className="overflow-x-auto">
            <table className="w-full text-left min-w-[640px]">
              <thead>
                <tr className="border-b border-gray-200 bg-gray-50">
                  {['', 'PID', 'Status', 'Projects', 'Latest project', 'Generated by', 'Created', 'Resolved'].map((h, i) => (
                    <th key={i} className="px-3 py-2 text-[11px] font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {filtered.length === 0 && (
                  <tr><td colSpan={8} className="px-3 py-10 text-center text-sm text-gray-400">
                    {search.trim() ? `No Project IDs match “${search.trim()}”.` : 'No Project IDs in this view yet.'}
                  </td></tr>
                )}
                {filtered.map(r => {
                  const meta = STATE_META[r.state] ?? { label: r.state, cls: 'bg-gray-100 text-gray-500' };
                  const open = openId === r.id;
                  return (
                    <Fragment key={r.id}>
                      <tr className="hover:bg-gray-50 cursor-pointer" onClick={() => setOpenId(open ? null : r.id)}>
                        <td className="px-3 py-2.5 text-gray-400">{open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</td>
                        <td className="px-3 py-2.5 text-xs font-mono font-medium text-gray-800 whitespace-nowrap">{r.pid}</td>
                        <td className="px-3 py-2.5">
                          <span className={clsx('inline-flex px-2 py-0.5 rounded-full text-[11px] font-medium', meta.cls)}>{meta.label}</span>
                        </td>
                        {/* How many projects sit under this PID — the returning-client count. */}
                        <td className="px-3 py-2.5 text-xs whitespace-nowrap">
                          {(r.roundCount ?? 0) > 1 ? (
                            <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-brand-50 text-brand-700 border border-brand-100 font-semibold">
                              {r.roundCount}
                            </span>
                          ) : <span className="text-gray-400">{r.roundCount ?? 0}</span>}
                        </td>
                        <td className="px-3 py-2.5 text-sm text-gray-700 max-w-[200px] truncate" title={r.project?.title ?? ''}>
                          {r.project ? r.project.title : <span className="text-gray-400">—</span>}
                        </td>
                        <td className="px-3 py-2.5 text-xs text-gray-600 whitespace-nowrap">{r.generatedBy}</td>
                        <td className="px-3 py-2.5 text-xs text-gray-500 whitespace-nowrap">{formatDateTimeIST(r.createdAt)}</td>
                        <td className="px-3 py-2.5 text-xs text-gray-500 whitespace-nowrap">{r.resolvedAt ? formatDateTimeIST(r.resolvedAt) : '—'}</td>
                      </tr>
                      {open && (
                        <tr className="bg-gray-50/60">
                          <td />
                          <td colSpan={7} className="px-3 py-3">
                            {(r.rounds?.length ?? 0) > 0 ? (
                              <div className="space-y-3">
                                {(r.roundCount ?? 0) > 1 && (
                                  <p className="text-[11px] text-gray-500">
                                    This Project ID holds <span className="font-semibold text-gray-700">{r.roundCount} projects</span> — the
                                    client has come back, and each piece of work is kept separately under the same number.
                                  </p>
                                )}
                                {(r.rounds ?? []).map(rd => (
                                  <div key={rd.id} className="rounded-lg border border-gray-200 bg-white p-3">
                                    <div className="flex items-center justify-between gap-2 flex-wrap mb-2">
                                      <div className="flex items-center gap-2 min-w-0">
                                        {(r.roundCount ?? 0) > 1 && (
                                          <span className="text-[10px] font-bold text-white bg-brand-500 rounded px-1.5 py-0.5 shrink-0">
                                            {rd.round}
                                          </span>
                                        )}
                                        <Link href={`/projects/${rd.id}`} onClick={e => e.stopPropagation()}
                                          className="text-sm font-semibold text-gray-900 hover:text-brand-600 hover:underline inline-flex items-center gap-1 truncate">
                                          {rd.title}<ExternalLink size={11} className="text-gray-300 shrink-0" />
                                        </Link>
                                      </div>
                                      <div className="flex items-center gap-1.5 shrink-0">
                                        {rd.type && <span className="text-[11px] px-1.5 py-0.5 rounded-full bg-indigo-50 text-indigo-700 border border-indigo-100">{projectTypeLabel(rd.type)}</span>}
                                        {rd.phase && <span className="text-[11px] px-1.5 py-0.5 rounded-full bg-gray-100 text-gray-600">{rd.phase}</span>}
                                        {rd.progress != null && <span className="text-[11px] text-gray-500 tabular-nums">{rd.progress}%</span>}
                                      </div>
                                    </div>
                                    <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-x-4 gap-y-1.5">
                                      <div><span className="text-gray-400">Priority</span><p className="text-gray-800">{rd.priority ?? '—'}</p></div>
                                      <div><span className="text-gray-400">Client</span><p className="text-gray-800">{rd.client ?? '—'}</p></div>
                                      <div><span className="text-gray-400">Start</span><p className="text-gray-800">{rd.startDate ? formatDate(rd.startDate) : '—'}</p></div>
                                      <div><span className="text-gray-400">End / deadline</span><p className="text-gray-800">{rd.dueDate ? formatDate(rd.dueDate) : '—'}</p></div>
                                      <div><span className="text-gray-400">Client deadline</span><p className="text-gray-800">{rd.clientDueDate ? formatDate(rd.clientDueDate) : '—'}</p></div>
                                      <div><span className="text-gray-400">Delivered</span><p className="text-gray-800">{rd.clientDeliveryDate ? formatDateTimeIST(rd.clientDeliveryDate) : '—'}</p></div>
                                      <div><span className="text-gray-400">Working hrs</span><p className="text-gray-800">{rd.workingHours != null ? `${rd.workingHours}h` : '—'}</p></div>
                                      <div><span className="text-gray-400">Actual hrs</span><p className="text-gray-800">{rd.actualHours != null ? `${rd.actualHours}h` : '—'}</p></div>
                                      <div><span className="text-gray-400">Created by</span><p className="text-gray-800">{rd.createdBy ?? '—'}</p></div>
                                      <div><span className="text-gray-400">Created</span><p className="text-gray-800">{rd.createdAt ? formatDate(rd.createdAt) : '—'}</p></div>
                                    </div>
                                    {rd.description && <p className="text-gray-600 mt-2 whitespace-pre-wrap">{rd.description}</p>}
                                    {(rd.patents?.length ?? 0) > 0 && (
                                      <div className="mt-2 flex flex-wrap gap-1.5">
                                        {(rd.patents ?? []).map((h, i) => <span key={i} className="px-2 py-0.5 rounded-md bg-amber-50 text-amber-700 font-mono ring-1 ring-amber-100">{h}</span>)}
                                      </div>
                                    )}
                                    <div className="mt-2">
                                      <span className="text-gray-400">Team</span>
                                      {(rd.members?.length ?? 0) > 0 ? (
                                        <div className="flex flex-wrap gap-1.5 mt-1">
                                          {(rd.members ?? []).map((m, i) => (
                                            <span key={i} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-50 border border-gray-200 text-gray-700">
                                              {m.name}<span className="text-gray-400">· {m.role}</span>
                                            </span>
                                          ))}
                                        </div>
                                      ) : <p className="text-gray-400">No active members.</p>}
                                    </div>
                                  </div>
                                ))}

                                {/* Actions apply to the LATEST project under this PID. */}
                                <div className="flex items-center gap-2 flex-wrap pt-1">
                                  <Link href={`/projects/${r.project!.id}`} onClick={e => e.stopPropagation()}
                                    className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-gray-200 bg-white text-gray-700 hover:bg-gray-50 font-medium">
                                    <ExternalLink size={13} /> Open {(r.roundCount ?? 0) > 1 ? 'latest project' : 'project'}
                                  </Link>
                                  {canReinit && !r.multiRound && (r.state === 'CLOSED' || r.state === 'COMPLETED') && (
                                    <button
                                      onClick={e => { e.stopPropagation(); reinitialize(r.project!.id, r.project!.title); }}
                                      disabled={reinitId === r.project!.id}
                                      title={`Reopen this matter under ${r.pid} — nothing is re-entered`}
                                      className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-brand-600 text-white hover:bg-brand-700 font-medium disabled:opacity-50">
                                      {reinitId === r.project!.id ? <Loader size={13} className="animate-spin" /> : <RotateCcw size={13} />}
                                      Re-initialize
                                    </button>
                                  )}
                                  {r.multiRound && (
                                    <span className="text-[11px] text-gray-400">
                                      A returning client gets a NEW project under {r.pid} — open the project and use “New project”.
                                    </span>
                                  )}
                                  {!r.multiRound && (r.state === 'CLOSED' || r.state === 'COMPLETED') && (
                                    <span className="text-[11px] text-gray-400">Reuses {r.pid} — the client keeps the number they already have.</span>
                                  )}
                                </div>
                              </div>
                            ) : (
                              <p className="text-xs text-gray-400">This PID isn’t attached to a project (reserved or discontinued-before-use).</p>
                            )}
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
