'use client';

import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import clsx from 'clsx';
import { X, Loader, KeyRound } from 'lucide-react';
import { api, type PidLedgerEntry } from '@/lib/api';
import { formatDateTimeIST } from '@/lib/date';

const STATUS_META: Record<PidLedgerEntry['status'], { label: string; cls: string }> = {
  ATTACHED:     { label: 'Working',      cls: 'bg-green-100 text-green-700' },
  RESERVED:     { label: 'Reserved',     cls: 'bg-amber-100 text-amber-700' },
  DISCONTINUED: { label: 'Discontinued', cls: 'bg-red-100 text-red-700' },
};

type FilterKey = 'All' | 'Working' | 'Discontinued' | 'Reserved';
const FILTERS: FilterKey[] = ['All', 'Working', 'Discontinued', 'Reserved'];

/** Admin/Super-Admin ledger of every Project ID — working, discontinued, and full history. */
export function PidLedgerModal({ onClose }: { onClose: () => void }) {
  const [filter, setFilter] = useState<FilterKey>('All');
  const { data: rows = [], isLoading, isError, refetch } = useQuery({
    queryKey: ['pid-ledger'],
    queryFn: () => api.projects.pidLedger(),
    staleTime: 15_000,
  });

  const filtered = useMemo(() => rows.filter(r => {
    if (filter === 'Working') return r.status === 'ATTACHED';
    if (filter === 'Discontinued') return r.status === 'DISCONTINUED';
    if (filter === 'Reserved') return r.status === 'RESERVED';
    return true;
  }), [rows, filter]);

  const counts = useMemo(() => ({
    working: rows.filter(r => r.status === 'ATTACHED').length,
    discontinued: rows.filter(r => r.status === 'DISCONTINUED').length,
    total: rows.length,
  }), [rows]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-3xl mx-4 max-h-[calc(100dvh-2rem)] flex flex-col">
        <div className="flex items-center justify-between px-6 py-5 border-b border-gray-100 shrink-0">
          <div>
            <h2 className="text-lg font-semibold text-gray-900 flex items-center gap-2"><KeyRound size={18} className="text-brand-600" /> Project ID Ledger</h2>
            <p className="text-sm text-gray-500 mt-0.5">
              {counts.working} working · {counts.discontinued} discontinued · {counts.total} total
            </p>
          </div>
          <button onClick={onClose} className="p-2 rounded-lg text-gray-400 hover:bg-gray-100"><X size={18} /></button>
        </div>

        <div className="px-6 pt-4 shrink-0 flex items-center gap-1.5">
          {FILTERS.map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className={clsx('px-3 py-1 text-xs font-medium rounded-full transition-colors',
                filter === f ? 'bg-brand-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200')}>
              {f}
            </button>
          ))}
        </div>

        <div className="px-6 py-4 overflow-auto">
          {isLoading && <p className="text-sm text-gray-400 flex items-center gap-2 py-8 justify-center"><Loader size={14} className="animate-spin" /> Loading…</p>}
          {!isLoading && isError && (
            <div className="text-sm text-gray-500 text-center py-8">
              <p className="text-red-500">Couldn’t load the PID ledger.</p>
              <button onClick={() => refetch()} className="mt-2 text-brand-600 hover:underline">Retry</button>
            </div>
          )}
          {!isLoading && !isError && (
            <div className="overflow-x-auto">
              <table className="w-full text-left min-w-[640px]">
                <thead>
                  <tr className="border-b border-gray-200 bg-gray-50">
                    {['PID', 'Status', 'Project', 'Generated by', 'Created', 'Resolved'].map(h => (
                      <th key={h} className="px-3 py-2 text-[11px] font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {filtered.length === 0 && (
                    <tr><td colSpan={6} className="px-3 py-10 text-center text-sm text-gray-400">No Project IDs in this view yet.</td></tr>
                  )}
                  {filtered.map(r => {
                    const meta = STATUS_META[r.status];
                    return (
                      <tr key={r.id} className="hover:bg-gray-50">
                        <td className="px-3 py-2.5 text-xs font-mono font-medium text-gray-800 whitespace-nowrap">{r.pid}</td>
                        <td className="px-3 py-2.5">
                          <span className={clsx('inline-flex px-2 py-0.5 rounded-full text-[11px] font-medium', meta.cls)}>{meta.label}</span>
                        </td>
                        <td className="px-3 py-2.5 text-sm text-gray-700 max-w-[200px] truncate" title={r.project?.title ?? ''}>
                          {r.project ? r.project.title : <span className="text-gray-400">—</span>}
                        </td>
                        <td className="px-3 py-2.5 text-xs text-gray-600 whitespace-nowrap">{r.generatedBy}</td>
                        <td className="px-3 py-2.5 text-xs text-gray-500 whitespace-nowrap">{formatDateTimeIST(r.createdAt)}</td>
                        <td className="px-3 py-2.5 text-xs text-gray-500 whitespace-nowrap">{r.resolvedAt ? formatDateTimeIST(r.resolvedAt) : '—'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
