import { Body, Controller, Delete, Get, Param, Patch, Post, Put, Query } from '@nestjs/common';
import { ProjectsService } from './projects.service';
import { ClientsProjectsService } from './projects.clients.service';
import {
  AddProjectRoundDto, ApprovalDto, AttachPidDto, CreateProjectDto, FulfillPidDto, MovePidDto,
  ReviewPidProjectDto, SetProjectClientDto, SetProjectPatentsDto, UpdateProjectDto,
} from './dto';
import {
  CreateProjectDto as CreateClientDto,
  MoveCidDto,
  UpdateProjectDto as UpdateClientDto,
} from './dto.clients';
import { RequirePermission } from '../../common/decorators/require-permission.decorator';
import { RequirePasscode } from '../../common/decorators/require-passcode.decorator';
import { RequireFlow } from '../../common/decorators/require-flow.decorator';
import { ActorContextService } from '../../common/context/actor-context.service';
import { WorkspaceFlowService } from '../workspace-flow/workspace-flow.service';
import { validateBody } from '../../common/validation/flow-body';
import type { MoveMode } from './pid-move';

/**
 * The preview's `mode` arrives as a query string, which can be anything. Anything that is not one
 * of the three is read as a plain reassign — the least surprising of them, and the one whose
 * refusals are the narrowest, so a garbled value can never widen what a caller is allowed to do.
 */
function asMoveMode(raw?: string): MoveMode {
  return raw === 'SPLIT' || raw === 'MERGE' ? raw : 'REASSIGN';
}

/**
 * /projects serves both workspace flows (docs/WORKSPACE_FLOWS.md):
 *
 *   • PROJECTS — ProjectsService (projects.service.ts), production's implementation: PIDs generated
 *     by an authority or requested from one, the patent portal's tagging, the PID ledger.
 *   • CLIENTS  — ClientsProjectsService (projects.clients.service.ts): a project is a client, its
 *     CID is issued on create, and the CID ledger is stored.
 *
 * A route both flows have dispatches on the caller's flow. Where the two flows accept different
 * bodies (create, update) the route takes the raw body and validates it against its own flow's
 * DTO, with the global pipe's options. A route one flow does not have carries @RequireFlow and
 * answers 404 to the other.
 */
@Controller('projects')
export class ProjectsController {
  constructor(
    private readonly projects: ProjectsService,
    private readonly clients: ClientsProjectsService,
    private readonly flows: WorkspaceFlowService,
    private readonly actor: ActorContextService,
  ) {}

  /** The implementation of the caller's flow, for routes whose signature is the same in both. */
  private async svc(): Promise<ProjectsService | ClientsProjectsService> {
    return (await this.flows.currentIsClients()) ? this.clients : this.projects;
  }

  @Post() @RequirePermission('project.create')
  async create(@Body() body: unknown) {
    if (await this.flows.currentIsClients()) {
      return this.clients.create(await validateBody(CreateClientDto, body));
    }
    return this.projects.create(await validateBody(CreateProjectDto, body));
  }

  // Org comes from the SESSION, never the client query — otherwise an oversight actor could
  // pass another org's id and enumerate its projects (S3). The ?organizationId= param the web
  // still sends is ignored.
  @Get()
  async list(
    @Query('phase') phase?: string,
    @Query('technologyDomain') technologyDomain?: string,
    @Query('sort') sort?: string,
  ) {
    return (await this.svc()).list(await this.actor.requireOrgId(), { phase, technologyDomain, sort });
  }

  /**
   * Project requests routed to me (as their manager) or, for admins, any pending one.
   * Org comes from the SESSION — a client-supplied org here would be a cross-tenant read.
   */
  /** Every project with its full detail (tasks, staffing, hours, delivery) — the Reports module. */
  @Get('full-report') @RequirePermission('report.view')
  async fullReport() {
    return (await this.svc()).fullReport(await this.actor.requireOrgId());
  }

  @Get('pending-approvals')
  async pendingApprovals() {
    return (await this.svc()).pendingApprovals(await this.actor.requireOrgId());
  }

  /** People who can be nominated as a project's manager (i.e. can approve it). Session-scoped. */
  @Get('eligible-managers')
  async eligibleManagers() {
    return (await this.svc()).eligibleManagers(await this.actor.requireOrgId());
  }

  /** The catalog of project types (built-ins + org custom templates) + their task templates. */
  @Get('types')
  async projectTypes() {
    return (await this.svc()).projectTypes(await this.actor.requireOrgId());
  }

  /** Built-in technology domains + the org's saved custom ones, alphabetical. */
  @Get('technology-domains')
  async technologyDomains() {
    return (await this.svc()).technologyDomains(await this.actor.requireOrgId());
  }

  // ── PROJECTS flow: the PID, generated by an authority or requested from one ──────────────────

  /** Non-binding preview of the PID the next created project would receive. */
  @Get('next-pid') @RequireFlow('PROJECTS')
  nextPid() {
    return this.projects.nextPid();
  }

  /** Reserve a Project ID (the "Generate PID" button) for 5 minutes. Authority only. */
  @Post('generate-pid') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async generatePid() {
    return this.projects.generatePid(await this.actor.requireOrgId(), this.actor.requireActorId());
  }

  /** My current un-attached PID (for the countdown), or null. Authority only. */
  @Get('pid-reservation') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async myReservation() {
    return this.projects.myReservation(await this.actor.requireOrgId(), this.actor.requireActorId());
  }

  /** The full PID ledger (working / discontinued / history). Admin + Super Admin only. */
  @Get('pid-ledger') @RequireFlow('PROJECTS') @RequirePermission('user.manage_access')
  async pidLedger() {
    return this.projects.allReservations(await this.actor.requireOrgId());
  }

  /** People who can assign a PID (project.generate_pid) — the request dropdown. */
  @Get('pid-authorities') @RequireFlow('PROJECTS') @RequirePermission('project.create')
  async pidAuthorities() {
    return this.projects.pidAuthorities(await this.actor.requireOrgId());
  }

  /** My incoming PID requests, as an authority — the fulfilment queue. */
  @Get('pid-requests') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async pidRequests() {
    return this.projects.pidRequestsFor(await this.actor.requireOrgId(), this.actor.requireActorId());
  }

  /** Verify/edit the pending project's details before assigning its PID (assignee-gated). */
  @Patch('pid-requests/:id/project') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async editPidRequestProject(@Param('id') id: string, @Body() dto: ReviewPidProjectDto) {
    return this.projects.editPidRequestProject(
      await this.actor.requireOrgId(), this.actor.requireActorId(), id, dto,
    );
  }

  /** Assign a PID to a pending-request project. */
  @Post('pid-requests/:id/fulfill') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async fulfillPidRequest(@Param('id') id: string, @Body() dto: FulfillPidDto) {
    return this.projects.fulfillPidRequest(
      await this.actor.requireOrgId(), this.actor.requireActorId(), id, dto.pid,
    );
  }

  /**
   * Existing Project IDs this project could be merged into — numbers in the same financial year
   * that still hold live work. Declared with the other static routes because `@Get(':id')` below
   * would otherwise swallow the path.
   */
  @Get(':id/pid-move/targets') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async pidMoveTargets(@Param('id') id: string) {
    return this.projects.pidMoveTargets(await this.actor.requireOrgId(), id);
  }

  /**
   * What a PID move WOULD do, before anyone commits to it: the number given up, the number taken,
   * whether the old one is retired, and which OTHER projects it renumbers. Read-only, so it is
   * permission-gated but deliberately not passcode-gated — asking for the step-up passcode to look
   * at a preview is how people learn to type it without reading.
   */
  @Get(':id/pid-move') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async pidMovePreview(
    @Param('id') id: string,
    @Query('mode') mode?: string,
    @Query('pid') pid?: string,
    @Query('intoProjectId') intoProjectId?: string,
  ) {
    return this.projects.pidMovePreview(await this.actor.requireOrgId(), id, {
      mode: asMoveMode(mode), pid, intoProjectId,
    });
  }

  // ── CLIENTS flow: the CID, issued on create, and its stored ledger ────────────────────────────

  /**
   * The CID ledger: every CID the organisation has ever issued — live, completed, deleted, merged,
   * retired or permanently deleted — with its clients, hours and full event timeline.
   * Admin, Super Admin and HR (user.manage_access), as the PID ledger it replaces was.
   */
  @Get('cid-ledger') @RequireFlow('CLIENTS') @RequirePermission('user.manage_access')
  async cidLedger() {
    return this.clients.cidLedger(await this.actor.requireOrgId());
  }

  /** Existing CIDs this client could be merged into — see pid-move/targets. */
  @Get(':id/cid-move/targets') @RequireFlow('CLIENTS') @RequirePermission('project.generate_pid')
  async cidMoveTargets(@Param('id') id: string) {
    return this.clients.cidMoveTargets(await this.actor.requireOrgId(), id);
  }

  /** What a CID move WOULD do — see pid-move. Read-only; not passcode-gated. */
  @Get(':id/cid-move') @RequireFlow('CLIENTS') @RequirePermission('project.generate_pid')
  async cidMovePreview(
    @Param('id') id: string,
    @Query('mode') mode?: string,
    @Query('cid') cid?: string,
    @Query('intoProjectId') intoProjectId?: string,
  ) {
    return this.clients.cidMovePreview(await this.actor.requireOrgId(), id, {
      mode: asMoveMode(mode), cid, intoProjectId,
    });
  }

  // ── Both flows ────────────────────────────────────────────────────────────────────────────────

  @Get(':id')
  async get(@Param('id') id: string) {
    return (await this.svc()).get(id);
  }

  @Patch(':id') @RequirePermission('project.update')
  async update(@Param('id') id: string, @Body() body: unknown) {
    if (await this.flows.currentIsClients()) {
      return this.clients.update(id, await validateBody(UpdateClientDto, body));
    }
    return this.projects.update(id, await validateBody(UpdateProjectDto, body));
  }

  /**
   * Replace the project's tagged patents. `project.update` + project access is the whole gate —
   * per the Phase 2 decision, tagging follows who may EDIT THE PROJECT, not who may see the
   * confidential patent portal. PROJECTS only: the CLIENTS flow has no patents.
   */
  @Put(':id/patents') @RequireFlow('PROJECTS') @RequirePermission('project.update')
  setPatents(@Param('id') id: string, @Body() dto: SetProjectPatentsDto) {
    return this.projects.setPatents(id, dto.patentIds ?? []);
  }

  /**
   * Name the project's client directly. Only possible while the project has NO tagged patents —
   * when it has them, they decide. The service additionally requires `patent.manage`, because a
   * client's identity is confidential in a way a patent handle is not. PROJECTS only: the CLIENTS
   * flow has no client codes.
   */
  @Put(':id/client') @RequireFlow('PROJECTS') @RequirePermission('project.update')
  setClient(@Param('id') id: string, @Body() dto: SetProjectClientDto) {
    return this.projects.setClient(id, dto.clientId ?? null);
  }

  @Post(':id/members') @RequirePermission('project.update')
  async addMember(@Param('id') id: string, @Body() body: { userId: string; projectRole?: string }) {
    return (await this.svc()).addMember(id, body.userId, body.projectRole);
  }

  @Delete(':id/members/:userId') @RequirePermission('project.update')
  async removeMember(@Param('id') id: string, @Param('userId') userId: string) {
    return (await this.svc()).removeMember(id, userId);
  }

  /** What the completion form should prefill "working hours" with (logged time, else estimates). */
  @Get(':id/completion-hours') @RequirePermission('project.view')
  async completionHours(@Param('id') id: string) {
    return (await this.svc()).completionHoursSuggestion(id);
  }

  /** Start ANOTHER project under this one's PID (CID) — the returning-client flow (Jaipur). */
  @Post(':id/rounds') @RequirePermission('project.create')
  async addRound(@Param('id') id: string, @Body() body: AddProjectRoundDto) {
    return (await this.svc()).addRound(id, body);
  }

  /** Every project sharing this one's PID (CID), oldest first — drives the PID page's cards. */
  @Get(':id/rounds')
  async rounds(@Param('id') id: string) {
    return (await this.svc()).roundsForProject(id);
  }

  @Post(':id/complete') @RequirePermission('project.update')
  async complete(@Param('id') id: string, @Body() body?: { clientDeliveryDate?: string; workingHours?: number; actualHours?: number }) {
    return (await this.svc()).complete(id, body);
  }

  @Post(':id/reopen') @RequirePermission('project.update')
  async reopen(@Param('id') id: string) {
    return (await this.svc()).reopen(id);
  }

  /** Re-initialize a COMPLETED project for a returning client — same PID (CID), existing data reused. */
  @Post(':id/reinitialize') @RequirePermission('project.update')
  async reinitialize(@Param('id') id: string) {
    return (await this.svc()).reinitialize(id);
  }

  /** Attach a fresh PID to a project that has none (e.g. a reopened one). Authority only. */
  @Post(':id/attach-pid') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid')
  async attachPid(@Param('id') id: string, @Body() dto: AttachPidDto) {
    return this.projects.attachPidToProject(
      await this.actor.requireOrgId(), this.actor.requireActorId(), id, dto.pid,
    );
  }

  /**
   * ── Correcting a Project ID (PROJECTS) / a CID (CLIENTS) ────────────────────────
   * Three routes for what is mechanically one operation, because they are three different claims
   * about what went wrong and each rules out a different mistake. Splitting checks that something
   * is actually sharing the number; merging checks that the destination actually holds work. One
   * route taking a "mode" would let a caller ask for a split and be given a merge.
   *
   * All three mint or retire a number the firm files work under, so all three carry the org
   * step-up passcode on top of `project.generate_pid` (Admin / Super Admin — a Manager REQUESTS a
   * PID, they do not issue one, and they certainly do not move one; in CLIENTS the permission is
   * labelled "Change CID").
   */

  /** The number on this project is wrong: move it to another one, or to a freshly minted one. */
  @Post(':id/pid/reassign') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid') @RequirePasscode()
  async reassignPid(@Param('id') id: string, @Body() dto: MovePidDto) {
    return this.projects.movePid(await this.actor.requireOrgId(), this.actor.requireActorId(), id, {
      mode: 'REASSIGN', pid: dto.pid, intoProjectId: dto.intoProjectId,
    });
  }

  /** This project is sharing a PID with others and is really a separate matter: give it its own. */
  @Post(':id/pid/split') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid') @RequirePasscode()
  async splitPid(@Param('id') id: string, @Body() dto: MovePidDto) {
    return this.projects.movePid(await this.actor.requireOrgId(), this.actor.requireActorId(), id, {
      mode: 'SPLIT', pid: dto.pid, intoProjectId: dto.intoProjectId,
    });
  }

  /** Two numbers, one matter: move this project under another's PID as its next round. */
  @Post(':id/pid/merge') @RequireFlow('PROJECTS') @RequirePermission('project.generate_pid') @RequirePasscode()
  async mergePid(@Param('id') id: string, @Body() dto: MovePidDto) {
    return this.projects.movePid(await this.actor.requireOrgId(), this.actor.requireActorId(), id, {
      mode: 'MERGE', pid: dto.pid, intoProjectId: dto.intoProjectId,
    });
  }

  /** This client should have a number of its own: move it to the next freshly issued CID. */
  @Post(':id/cid/reassign') @RequireFlow('CLIENTS') @RequirePermission('project.generate_pid') @RequirePasscode()
  async reassignCid(@Param('id') id: string, @Body() dto: MoveCidDto) {
    return this.clients.moveCid(await this.actor.requireOrgId(), this.actor.requireActorId(), id, {
      mode: 'REASSIGN', cid: dto.cid, intoProjectId: dto.intoProjectId,
    });
  }

  /** This client shares a CID with others and is really a separate matter: give it its own. */
  @Post(':id/cid/split') @RequireFlow('CLIENTS') @RequirePermission('project.generate_pid') @RequirePasscode()
  async splitCid(@Param('id') id: string, @Body() dto: MoveCidDto) {
    return this.clients.moveCid(await this.actor.requireOrgId(), this.actor.requireActorId(), id, {
      mode: 'SPLIT', cid: dto.cid, intoProjectId: dto.intoProjectId,
    });
  }

  /** Two numbers, one matter: move this client under another's CID as its next round. */
  @Post(':id/cid/merge') @RequireFlow('CLIENTS') @RequirePermission('project.generate_pid') @RequirePasscode()
  async mergeCid(@Param('id') id: string, @Body() dto: MoveCidDto) {
    return this.clients.moveCid(await this.actor.requireOrgId(), this.actor.requireActorId(), id, {
      mode: 'MERGE', cid: dto.cid, intoProjectId: dto.intoProjectId,
    });
  }

  @Post(':id/approve') @RequirePermission('project.approve')
  async approve(@Param('id') id: string, @Body() dto: ApprovalDto) {
    return (await this.svc()).decide(id, true, dto);
  }

  @Post(':id/reject') @RequirePermission('project.approve')
  async reject(@Param('id') id: string, @Body() dto: ApprovalDto) {
    return (await this.svc()).decide(id, false, dto);
  }

  @Delete(':id') @RequirePermission('project.delete')
  async remove(@Param('id') id: string) {
    return (await this.svc()).softDelete(id);
  }
}
